version: "3.1"

services:
  api:
    container_name: api
    restart: on-failure
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"
    command: ['yarn', 'dev']
  
  nginx:
    image: nginx:alpine
    restart: always
    container_name: nginx
    depends_on:
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certificate.pem:/etc/nginx/conf.d/certificate.pem 
      - ./nginx/key.pem:/etc/nginx/conf.d/key.pem 
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"
  
  redis:
    container_name: redis
    restart: always
    image: redis:latest
    volumes:
      - redis:/data/
    ports:
      - "6379:6379"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

networks: 
  backend:
    driver: bridge
    
volumes:
  redis:
  mongo:
  nginx:
