version: "3"

services:
  api:
    container_name: api
    restart: on-failure
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "./app:/src/app"
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"
    command: yarn test
    environment:
        - NODE_ENV=test
        - PORT=3000
        - MONGO_DB_TESTS=mongodb://mongo:27017/manga_stream_tests
        - REDIS_PORT=6379
        - REDIS_EXPIRE=1800
        - REDIS_HOST=redis

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    depends_on:
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certificate.pem:/etc/nginx/conf.d/certificate.pem
      - ./nginx/key.pem:/etc/nginx/conf.d/key.pem
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis:/data/
    ports:
      - "6379:6379"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

networks:
  backend:
    driver: bridge

volumes:
  redis:
  mongo:
  nginx:
