version: "3"

services:
  sut:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "./app:/src/app"
    links:
      - mongo
      - redis
    depends_on:
      - redis
      - mongo
    environment:
      - NODE_ENV=test
      - PORT=3000
      - MONGO_DB_TESTS=mongodb://mongo:27017/manga_stream_tests
      - REDIS_PORT=6379
      - REDIS_EXPIRE=1800
      - REDIS_HOST=redis
    networks:
      - back-tier
    command: yarn test

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - back-tier

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis:/data/
    ports:
      - "6379:6379"
    networks:
      - back-tier

volumes:
  mongo:
  redis:

networks:
  back-tier:
